In [1]:
import pandas as pd

In [3]:
df = pd.read_csv("/Users/kushalshakya/Desktop/Github/DataAnalysis_Class/Python/Pandas/titanic.csv")

In [4]:
df.head(15)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
12,13,0,3,"Saundercock, Mr. William Henry",male,20.0,0,0,A/5. 2151,8.0500,NaN,S
13,14,0,3,"Andersson, Mr. Anders Johan",male,39.0,1,5,347082,31.2750,NaN,S
14,15,0,3,"Vestrom, Miss. Hulda Amanda Adolfina",female,14.0,0,0,350406,7.8542,NaN,S

In [5]:
df.tail(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1299,1300,1,3,"Riordan, Miss. Johanna Hannah""""",female,NaN,0,0,334915,7.7208,NaN,Q
1300,1301,1,3,"Peacock, Miss. Treasteall",female,3.0,1,1,SOTON/O.Q. 3101315,13.7750,NaN,S
1301,1302,1,3,"Naughton, Miss. Hannah",female,NaN,0,0,365237,7.7500,NaN,Q
1302,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
1303,1304,1,3,"Henriksson, Miss. Jenny Lovisa",female,28.0,0,0,347086,7.7750,NaN,S
1304,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
1305,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
1306,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
1307,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
1308,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [6]:
df.shape

(1309, 12)

In [ ]:
# try to uplaod the another datasets and try to find out shape info and other items

x = pd.read_csv("/Users/kushalshakya/Desktop/Github/DataAnalysis_Class/Python/Pandas/data.csv")

In [8]:
x.shape

(50, 3)

###  test with head, tail ,shape ,info describe

In [10]:
x.head(5)

     Name  Age  Score
0  Ananda   22     85
1    Sita   21     90
2     Ram   23     88
3    Gita   20     76
4    Hari   22     92

In [11]:
x.tail(5)

      Name  Age  Score
45   Pawan   21     84
46  Monika   23     88
47   Ashok   20     81
48  Preeti   22     90
49   Sonia   21     85

In [13]:
x.shape

(50, 3)

In [15]:
x.info

<bound method DataFrame.info of        Name  Age  Score
0    Ananda   22     85
1      Sita   21     90
2       Ram   23     88
3      Gita   20     76
4      Hari   22     92
5      Nita   21     81
6      Ravi   23     87
7     Pooja   20     79
8     Kiran   22     84
9      Maya   21     90
10     Amit   23     86
11    Sneha   20     78
12    Rohan   22     91
13    Anita   21     83
14   Bikash   23     89
15    Nisha   20     80
16    Rahul   22     88
17     Puja   21     82
18    Suman   23     90
19   Kavita   20     77
20    Arjun   22     85
21     Neha   21     84
22    Sagar   23     92
23     Rita   20     79
24   Manish   22     88
25   Sunita   21     81
26   Deepak   23     90
27    Priya   20     83
28    Rohit   22     87
29    Alina   21     86
30    Vikas   23     91
31     Mina   20     78
32    Nabin   22     84
33    Komal   21     82
34   Dipesh   23     89
35    Laxmi   20     80
36  Prakash   22     88
37     Isha   21     85
38    Niraj   23     92
39     Asha   20     77
40    Suraj   22     90
41     Riya   21     83
42  Santosh   23     91
43   Anjali   20     79
44   Hemant   22     86
45    Pawan   21     84
46   Monika   23     88
47    Ashok   20     81
48   Preeti   22     90
49    Sonia   21     85>

In [16]:
x.describe

<bound method DataFrame.describe of        Name  Age  Score
0    Ananda   22     85
1      Sita   21     90
2       Ram   23     88
3      Gita   20     76
4      Hari   22     92
5      Nita   21     81
6      Ravi   23     87
7     Pooja   20     79
8     Kiran   22     84
9      Maya   21     90
10     Amit   23     86
11    Sneha   20     78
12    Rohan   22     91
13    Anita   21     83
14   Bikash   23     89
15    Nisha   20     80
16    Rahul   22     88
17     Puja   21     82
18    Suman   23     90
19   Kavita   20     77
20    Arjun   22     85
21     Neha   21     84
22    Sagar   23     92
23     Rita   20     79
24   Manish   22     88
25   Sunita   21     81
26   Deepak   23     90
27    Priya   20     83
28    Rohit   22     87
29    Alina   21     86
30    Vikas   23     91
31     Mina   20     78
32    Nabin   22     84
33    Komal   21     82
34   Dipesh   23     89
35    Laxmi   20     80
36  Prakash   22     88
37     Isha   21     85
38    Niraj   23     92
39     Asha   20     77
40    Suraj   22     90
41     Riya   21     83
42  Santosh   23     91
43   Anjali   20     79
44   Hemant   22     86
45    Pawan   21     84
46   Monika   23     88
47    Ashok   20     81
48   Preeti   22     90
49    Sonia   21     85>