### Pandas: Series and DataFrame

Learn the basics with small examples, then solve the practice questions in the empty code cells.

In [1]:
import pandas as pd

#### 1. Pandas Series

A **Series** is a one-dimensional labeled array (like a single table column with an index).

**Create a Series**

In [2]:
s = pd.Series([10, 20, 30, 40])
s

0    10
1    20
2    30
3    40
dtype: int64

**Create a Series with a custom index**

In [3]:
marks = pd.Series([85, 90, 88], index=["Ananda", "Sita", "Ram"])
marks

Ananda    85
Sita      90
Ram       88
dtype: int64

**Access a value by position**

In [4]:
# Get the first value by position
marks.iloc[0]

np.int64(85)

#### Series Practice

Solve each question in the code cell provided. Do not change the examples above.

In [5]:
# Q1. Create a Series containing 5, 10, 15, and 20. Display it.
# Write your code below:

num = pd.Series([5,10,15,20])
num

0     5
1    10
2    15
3    20
dtype: int64

In [11]:
# Q2. Display the second value from the Series named s.
# Write your code below:

s = pd.Series([1,2,3,4,5])
print(s.iloc[1])

2

In [15]:
# Q3. Display Sita's marks from the Series named marks.
# Write your code below:

print(marks)
marks.loc["Sita"]

Ananda    85
Sita      90
Ram       88
dtype: int64

np.int64(90)

#### 2. Pandas DataFrame

A **DataFrame** is a two-dimensional table made of rows and columns (similar to an Excel or SQL table).

**Create a DataFrame**

In [16]:
df = pd.DataFrame({
    "Name": ["Ananda", "Sita", "Ram"],
    "Age": [22, 21, 23],
    "Score": [85, 90, 85]
})

df

     Name  Age  Score
0  Ananda   22     85
1    Sita   21     90
2     Ram   23     85

#### Select Columns

- A single column returns a **Series**.
- Multiple columns return a **DataFrame**.

In [17]:
# Select one column
df["Age"]

0    22
1    21
2    23
Name: Age, dtype: int64

In [18]:
# Select multiple columns
df[["Name", "Score"]]

     Name  Score
0  Ananda     85
1    Sita     90
2     Ram     85

#### Common DataFrame Methods

Use these methods to quickly explore a DataFrame.

In [19]:
# First 2 rows
df.head(2)

     Name  Age  Score
0  Ananda   22     85
1    Sita   21     90

In [20]:
# Last 2 rows
df.tail(2)

   Name  Age  Score
1  Sita   21     90
2   Ram   23     85

In [21]:
# Number of rows and columns
df.shape

(3, 3)

In [22]:
# One random row
df.sample(1)

     Name  Age  Score
0  Ananda   22     85

#### DataFrame Practice

Use the DataFrame named `df` above. Write your answers in the cells below.

In [26]:
# Q1. Display only the Name column.
# Write your code below:

df[["Name"]]

     Name
0  Ananda
1    Sita
2     Ram

In [25]:
# Q2. Display the Name and Age columns together.
# Write your code below:

df[["Name","Age"]]

     Name  Age
0  Ananda   22
1    Sita   21
2     Ram   23

In [27]:
# Q3. Display the last 2 rows of the DataFrame.
# Write your code below:

df.tail(2)

   Name  Age  Score
1  Sita   21     90
2   Ram   23     85

In [28]:
# Q4. Display the number of rows and columns in the DataFrame.
# Write your code below:

df.shape

(3, 3)

#### 3. Practice with a Larger DataFrame

Use the following sample student dataset for exploring and saving data.

In [29]:
df = pd.DataFrame({
    "Name": [
        "Ananda", "Sita", "Ram", "Gita", "Hari", "Nita", "Ravi", "Pooja", "Kiran", "Maya",
        "Amit", "Sneha", "Rohan", "Anita", "Bikash", "Nisha", "Rahul", "Puja", "Suman", "Kavita",
        "Arjun", "Neha", "Sagar", "Rita", "Manish", "Sunita", "Deepak", "Priya", "Rohit", "Alina",
        "Vikas", "Mina", "Nabin", "Komal", "Dipesh", "Laxmi", "Prakash", "Isha", "Niraj", "Asha",
        "Suraj", "Riya", "Santosh", "Anjali", "Hemant", "Pawan", "Monika", "Ashok", "Preeti", "Sonia"
    ],
    "Age": [
        22, 21, 23, 20, 22, 21, 23, 20, 22, 21,
        23, 20, 22, 21, 23, 20, 22, 21, 23, 20,
        22, 21, 23, 20, 22, 21, 23, 20, 22, 21,
        23, 20, 22, 21, 23, 20, 22, 21, 23, 20,
        22, 21, 23, 20, 22, 21, 23, 20, 22, 21
    ],
    "Score": [
        85, 90, 88, 76, 92, 81, 87, 79, 84, 90,
        86, 78, 91, 83, 89, 80, 88, 82, 90, 77,
        85, 84, 92, 79, 88, 81, 90, 83, 87, 86,
        91, 78, 84, 82, 89, 80, 88, 85, 92, 77,
        90, 83, 91, 79, 86, 84, 88, 81, 90, 85
    ]
})

df

       Name  Age  Score
0    Ananda   22     85
1      Sita   21     90
2       Ram   23     88
3      Gita   20     76
4      Hari   22     92
5      Nita   21     81
6      Ravi   23     87
7     Pooja   20     79
8     Kiran   22     84
9      Maya   21     90
10     Amit   23     86
11    Sneha   20     78
12    Rohan   22     91
13    Anita   21     83
14   Bikash   23     89
15    Nisha   20     80
16    Rahul   22     88
17     Puja   21     82
18    Suman   23     90
19   Kavita   20     77
20    Arjun   22     85
21     Neha   21     84
22    Sagar   23     92
23     Rita   20     79
24   Manish   22     88
25   Sunita   21     81
26   Deepak   23     90
27    Priya   20     83
28    Rohit   22     87
29    Alina   21     86
30    Vikas   23     91
31     Mina   20     78
32    Nabin   22     84
33    Komal   21     82
34   Dipesh   23     89
35    Laxmi   20     80
36  Prakash   22     88
37     Isha   21     85
38    Niraj   23     92
39     Asha   20     77
40    Suraj   22     90
41     Riya   21     83
42  Santosh   23     91
43   Anjali   20     79
44   Hemant   22     86
45    Pawan   21     84
46   Monika   23     88
47    Ashok   20     81
48   Preeti   22     90
49    Sonia   21     85

**Explore the dataset**

In [30]:
# First 10 rows
df.head(10)

     Name  Age  Score
0  Ananda   22     85
1    Sita   21     90
2     Ram   23     88
3    Gita   20     76
4    Hari   22     92
5    Nita   21     81
6    Ravi   23     87
7   Pooja   20     79
8   Kiran   22     84
9    Maya   21     90

In [31]:
# Last 10 rows
df.tail(10)

       Name  Age  Score
40    Suraj   22     90
41     Riya   21     83
42  Santosh   23     91
43   Anjali   20     79
44   Hemant   22     86
45    Pawan   21     84
46   Monika   23     88
47    Ashok   20     81
48   Preeti   22     90
49    Sonia   21     85

In [32]:
# 5 random rows
df.sample(5)

     Name  Age  Score
28  Rohit   22     87
16  Rahul   22     88
32  Nabin   22     84
21   Neha   21     84
47  Ashok   20     81

In [33]:
# Column names, non-null counts, and data types
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    50 non-null     str
 1   Age     50 non-null     int64
 2   Score   50 non-null     int64
dtypes: int64(2), str(1)
memory usage: 1.3 KB

In [34]:
# Summary statistics for numerical columns
df.describe()

             Age      Score
count  50.000000  50.000000
mean   21.500000  85.080000
std     1.111168   4.606296
min    20.000000  76.000000
25%    21.000000  81.250000
50%    21.500000  85.000000
75%    22.000000  89.000000
max    23.000000  92.000000

**Save the DataFrame as a CSV file**

In [36]:
# index=False avoids saving row indexes as an extra column
df.to_csv("data.csv", index=False)

#### Final Practice

Write your own code in the space under each question.

In [39]:
# Q1. Create a new DataFrame using Python lists with Name, Age, and Score for 3 new students.
# Write your code below:

dfr = pd.DataFrame({
    "Name" :['ram', 'shyam','hari'],
    "Age" : [13,14,15],
    "Score" : [1,2,3]
})

dfr

    Name  Age  Score
0    ram   13      1
1  shyam   14      2
2   hari   15      3

In [53]:
# Q2. Display the first 5 and last 5 rows from the large DataFrame named df.
# Write your code below:


print(df.head(5), df.tail(5))

     Name  Age  Score
0  Ananda   22     85
1    Sita   21     90
2     Ram   23     88
3    Gita   20     76
4    Hari   22     92       Name  Age  Score
45   Pawan   21     84
46  Monika   23     88
47   Ashok   20     81
48  Preeti   22     90
49   Sonia   21     85

#### Notes and Further Reading

Write a short comparison of **Series vs. DataFrame** (including one code example of each). You can refer to the [official pandas documentation](https://pandas.pydata.org/docs/).

In [ ]:
# Series vs. DataFrame: write an example of each below.